DROP TABLE IF EXISTS corpora;
DROP TABLE IF EXISTS structures;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS queries;
DROP TABLE IF EXISTS proximities;
DROP TABLE IF EXISTS search_types;
DROP TABLE IF EXISTS within_structures;
DROP TABLE IF EXISTS filter_atts;
DROP TABLE IF EXISTS filters;
DROP TABLE IF EXISTS filter_group_include;
DROP TABLE IF EXISTS filter_range_include;
DROP TABLE IF EXISTS group_atts;
DROP TABLE IF EXISTS output_atts;
DROP TABLE IF EXISTS analysis_files;
CREATE TABLE corpora (c_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, cqp_name VARCHAR(32) NOT NULL UNIQUE, display_name VARCHAR(64) NOT NULL UNIQUE, text_id_att VARCHAR(32) NOT NULL, PRIMARY KEY (c_id)) DEFAULT CHARSET=utf8, DEFAULT COLLATE=utf8_unicode_ci;
CREATE TABLE structures (c_id SMALLINT UNSIGNED NOT NULL, s_name VARCHAR(16) NOT NULL, s_id MEDIUMINT UNSIGNED NOT NULL, text_id MEDIUMINT UNSIGNED NOT NULL, cpos_start INT UNSIGNED NOT NULL, cpos_end INT UNSIGNED NOT NULL, PRIMARY KEY (c_id, s_name, s_id), INDEX (c_id, s_name), INDEX (c_id, s_name, text_id), UNIQUE INDEX (c_id, s_name, cpos_start), UNIQUE INDEX (c_id, s_name, text_id, cpos_start), UNIQUE INDEX (c_id, s_name, cpos_end), UNIQUE INDEX (c_id, s_name, text_id, cpos_end), UNIQUE INDEX (c_id, s_name, cpos_start, cpos_end), UNIQUE INDEX (c_id, s_name, text_id, cpos_start, cpos_end), INDEX (c_id), INDEX(c_id, text_id, cpos_start, cpos_end)) DEFAULT CHARSET=utf8, DEFAULT COLLATE=utf8_unicode_ci;
CREATE TABLE users (user_id smallint unsigned NOT NULL AUTO_INCREMENT, username varchar(32) NOT NULL, password varbinary(32) NOT NULL, cookie varbinary(32) NOT NULL, ip varbinary(15) NOT NULL, email varchar(64) NOT NULL, active tinyint(1) NOT NULL DEFAULT 0, PRIMARY KEY (user_id), UNIQUE (username), UNIQUE (email)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE permissions (user_id smallint unsigned NOT NULL, c_id smallint unsigned NOT NULL, PRIMARY KEY (user_id, c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE queries (query_id mediumint unsigned NOT NULL AUTO_INCREMENT, c_id smallint unsigned NOT NULL, user_id smallint unsigned NOT NULL, query_name varchar(32) NOT NULL, ts DATETIME NOT NULL, query_text TEXT NOT NULL, PRIMARY KEY (query_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE proximities (proximity_id mediumint unsigned NOT NULL AUTO_INCREMENT, c_id smallint unsigned NOT NULL, user_id smallint unsigned NOT NULL, proximity_name varchar(32) NOT NULL, ts DATETIME NOT NULL, words_left SMALLINT UNSIGNED, words_right SMALLINT UNSIGNED, within_type VARCHAR(16), within_count TINYINT UNSIGNED, PRIMARY KEY (proximity_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE search_types (c_id smallint unsigned NOT NULL, attribute varchar(32) NOT NULL, description varchar(64) NOT NULL, display_order smallint unsigned NOT NULL, PRIMARY KEY (c_id, attribute), INDEX (c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE within_structures (c_id smallint unsigned NOT NULL, structure varchar(32) NOT NULL, display_order smallint unsigned NOT NULL, PRIMARY KEY (c_id, structure), INDEX (c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE filter_atts (c_id SMALLINT UNSIGNED NOT NULL, source_table ENUM('texts', 'pntypes', 'pntokens') NOT NULL, table_column VARCHAR(32) NOT NULL, search_type ENUM('group', 'range') NOT NULL, display_order smallint unsigned NOT NULL, PRIMARY KEY (c_id, table_column), INDEX (c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE filters (filter_id mediumint unsigned NOT NULL AUTO_INCREMENT, c_id smallint unsigned NOT NULL, user_id smallint unsigned NOT NULL, filter_name varchar(32) NOT NULL, ts DATETIME NOT NULL, PRIMARY KEY (filter_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE filter_range_include (filter_id mediumint unsigned NOT NULL, field varchar(32) NOT NULL, minimum DOUBLE, maximum DOUBLE, PRIMARY KEY (filter_id, field)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE filter_group_include (filter_id mediumint unsigned NOT NULL, field varchar(32) NOT NULL, val varchar(32) NOT NULL, PRIMARY KEY (filter_id, field, val)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE group_atts (c_id SMALLINT UNSIGNED NOT NULL, text_table_column VARCHAR(32) NOT NULL, display_order smallint unsigned NOT NULL, PRIMARY KEY (c_id, text_table_column), INDEX (c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE output_atts (c_id SMALLINT UNSIGNED NOT NULL, source_table ENUM('texts', 'pntypes', 'pntokens') NOT NULL, table_column VARCHAR(32) NOT NULL, PRIMARY KEY (c_id, table_column), INDEX (c_id)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;
CREATE TABLE analysis_files (query_id MEDIUMINT UNSIGNED NOT NULL, proximity_id MEDIUMINT UNSIGNED NOT NULL, filter_id MEDIUMINT UNSIGNED NOT NULL, filename varchar(64) NOT NULL, description varchar(128) NOT NULL, size varchar(16) NOT NULL, ts DATETIME NOT NULL, PRIMARY KEY (query_id, proximity_id, filter_id, filename)) DEFAULT charset=utf8, DEFAULT collate=utf8_unicode_ci;